directories:
  mirror_module_path: True
  output: "/Users/kiser/Documents/Coding/Repos/videos"
  raster_images: "/Users/kiser/Documents/Coding/Repos/images/raster"
  vector_images: "/Users/kiser/Documents/Coding/Repos/images/vector"
  pi_creature_images: "/Users/kiser/Documents/Coding/Repos/images/pi_creature/svg"
  sounds: "/Users/kiser/Documents/Coding/Repos/sounds"
  data: "/Users/kiser/Documents/Coding/Repos/data"
  temporary_storage: "/Users/kiser/Documents/Coding/Repos/manim_cache"
universal_import_line: "from manim_imports_ext import *"
# tex:
#   executable: "xelatex -no-pdf"
#   template_file: "ctex_template.tex"
#   intermediate_filetype: "xdv"
style:
  font: "CMU Serif"
  background_color: "#000000"
camera_qualities:
  high:
    resolution: "1920x1080"
    frame_rate: 60
  default_quality: "ultra_high"
window_position: UR
window_monitor: 0
full_screen: False